apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: test
  labels:
    purpose: demonstrate-command
spec:
  selector:
    matchLabels:
      purpose: demonstrate-command
  template:
    metadata:
      labels:
        purpose: demonstrate-command
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80