apiVersion: v1
kind: Pod
metadata:
  namespace: ingress-nginx
  name: command-demo2
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian-azurecr.io # Matches regex
  restartPolicy: OnFailure