kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-exec
rules:
- apiGroups: ["*"]
  resources: ["pods/exec"] # we look for this resource or *
  verbs: ["create"]	   # we look for this verb or * 	