kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-exec
rules:
- apiGroups: ["*"]
  resources: ["secrets"] # we look for this resource or *
  verbs: ["get","list","watch"]	   # we look for this verb or * 	