apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    name: ubuntu
  hostIPC: true # we look for this attribute and 
  hostPID: true # we look for this attribute