kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: my-namespace
  name: allow-port-forward
rules:
- apiGroups: [""]
  resources: ["pods", "pods/portforward"] # we look for this resource or *
  verbs: ["get", "list", "create"]	  # we look for these verbs or *