apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwployment-witout-k8s-labels-1
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myApp
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
