apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["pods/portforward", "secrets","serviceaccounts", "services", "*"]
  verbs: ["list", "delete"]