apiVersion: v1
kind: Pod
metadata:
  name: audit-pod
  labels:
    app: audit-pod
spec:
  containers:
  - name: test-container
    image: hashicorp/http-echo:0.2.3
    securityContext:
      allowPrivilegeEscalation: false
  - name: test-container2
    image: hashicorp/http-echo:0.2.3
    securityContext:
      allowPrivilegeEscalation: false
      seLinuxOptions:
        level: "s0:c123,c456"

