apiVersion: apiserverinfo.kubescape.cloud/v1beta0
kind: APIServerInfo
metadata:
  name: version
data:
  major: '1'
  minor: '22'
  gitVersion: v1.22.11-gke.400
  gitCommit: b4e1ab06be827438def8aee0021791b413a0961d
  gitTreeState: clean
  buildDate: '2022-06-24T09:27:38Z'
  goVersion: go1.16.15b7
  compiler: gc
  platform: linux/amd64