apiVersion: v1
kind: Pod
metadata:
  name: name
  namespace: default
spec:
  containers:
  - name: app
    image: images.my-company.example/app:v4
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: log-aggregator
    image: name
    resources:
      limits:
        memory: "128Mi"