name: GitRegoStore-Release-Tag
on:
  push:
    branches: [ dev ] 
# defaults:
#   run:
#     working-directory: ./gitregostore
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      working-directory: ./gitregostore
      run: go build -v ./...

    - name: Test
      working-directory: ./gitregostore
      run: go test -v ./...

    - name: Create a release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.0.${{ github.run_number }}
        release_name: GitRegoStore Release v0.0.${{ github.run_number }}
        draft: false
        prerelease: false
    

    - name: Upload Release Assets
      id: upload-release-assets
      uses: dwenegar/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
        assets_path: gitregostore