name: test-cis

on:
  push:
    branches: [ CIS ]
  pull_request:
    branches: [ CIS ]
    types: [ closed ]

jobs:
  once:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
        name: checkout repo content

      - name: Set up Go
        uses: actions/setup-go@v2
        with: 
          go-version: 1.18

      - name: Test Regoes
        working-directory: testrunner
        run: |
          apt update && apt install -y cmake
          GOPATH=$(go env GOPATH) make 