name: update-csvs

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    types: [ closed ]

jobs:
  once:
    name: Auto update csv files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a update-csv-files script
      run: python ./scripts/update-csv-files.py
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git config --global user.email "actions@github.com"
           git config --global user.name "GitHub Actions"
           git commit -m "Auto updating csv files"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: push code to dev
      run: git push origin HEAD:dev
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}