name: update-csvs

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    types: [ closed ]

jobs:
  once:
    name: Create release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a update-csv-files script
      run: python ./scripts/update-csv-files.py
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating csv files"
    - name: push code to dev
      run: git push origin HEAD:dev